# **Coal Supply Network Optimization in India's Energy Capital**

#### I have created a single notebook for entire problem-solving from adding new variables, computing and optimizing the problem.

## **Loading the data**

In [155]:
import pandas as pd 
import numpy as np
import os
import scipy.optimize

In [156]:
base_path = os.path.dirname(os.getcwd())

In [157]:
distances = pd.read_csv("../Datasets/optimization_Dataset - Distances.csv")
freight = pd.read_csv("../Datasets/Optimization_Dataset - Frieght_Rates.csv")
mines = pd.read_csv("../Datasets/Optimization_Dataset - Mines.csv")
plants = pd.read_csv("../Datasets/Optimization_Dataset - Plants.csv")

In [158]:
print(distances.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Mine \ Plant', 'P1 (Vindhyachal)', 'P2 (Singrauli STPS)',
       'P3 (Rihand)', 'P4 (Obra)', 'P5 (Anpara)', 'P6 (Renusagar)',
       'P7 (Essar Mahan)'],
      dtype='object')>

In [159]:
distances.head()

,Mine \ Plant,P1 (Vindhyachal),P2 (Singrauli STPS),P3 (Rihand),P4 (Obra),P5 (Anpara),P6 (Renusagar),P7 (Essar Mahan)
0,M1 (Jayant),17.3,17.1,39.8,76.2,23.5,23.8,85.6
1,M2 (Dudhichua),66.5,66.3,89.0,55.5,43.2,43.5,43.2
2,M3 (Nigahi),17.3,17.1,39.8,76.2,23.5,23.8,85.6
3,M4 (Krishnashila),14.3,14.1,36.8,76.6,23.9,24.2,86.0
4,M5 (Bina),22.5,22.3,45.0,66.6,13.9,14.1,75.9

In [160]:
distances.set_index("Mine \\ Plant", inplace=True)
distances.head()

,P1 (Vindhyachal),P2 (Singrauli STPS),P3 (Rihand),P4 (Obra),P5 (Anpara),P6 (Renusagar),P7 (Essar Mahan)
Mine \ Plant,,,,,,,
M1 (Jayant),17.3,17.1,39.8,76.2,23.5,23.8,85.6
M2 (Dudhichua),66.5,66.3,89.0,55.5,43.2,43.5,43.2
M3 (Nigahi),17.3,17.1,39.8,76.2,23.5,23.8,85.6
M4 (Krishnashila),14.3,14.1,36.8,76.6,23.9,24.2,86.0
M5 (Bina),22.5,22.3,45.0,66.6,13.9,14.1,75.9

In [161]:
mines['Monthly Supply (tonnes)'] = (
    mines['Monthly Supply (tonnes)']
    .astype(str)
    .str.replace(',', '')      # Remove commas
    .str.replace('+', '')      # Remove + signs
    .str.replace('~', '')      # Remove ~ signs
    .str.replace('-', '')      # Remove hyphens
    .str.strip()               
    .astype(float)
)

## **Calculating Cost Matrix**

Cost matrix is a table where each cell tells you: 'How many rupees it costs to send 1 tonne of coal from this mine to that plant.'

In [162]:
def get_freight_rate(d):
    if d <= 100: return 216
    elif d <= 125: return 389.6
    elif d <= 150: return 448.9
    elif d <= 175: return 488.7
    elif d <= 200: return 532.2
    elif d <= 275: return 672.5
    elif d <= 350: return 797.2
    elif d <= 425: return 926
    elif d <= 500: return 1054.7
    elif d <= 600: return 1228
    elif d <= 700: return 1398.7
    elif d <= 730: return 1435.6
    else: return 1484


cost_matrix = distances.copy() # Cost Matrix Created Here
CTS = 55 # CTS = Coal Terminal Surcharge

for mine in distances.index:
    for plant in distances.columns:
        d = distances.loc[mine, plant]
        cost_matrix.loc[mine, plant] = get_freight_rate(d) + (CTS if d > 100 else 0)

print(cost_matrix.head())

                   P1 (Vindhyachal)  P2 (Singrauli STPS)  P3 (Rihand)  \
Mine \ Plant
M1 (Jayant)                   216.0                216.0        216.0
M2 (Dudhichua)                216.0                216.0        216.0
M3 (Nigahi)                   216.0                216.0        216.0
M4 (Krishnashila)             216.0                216.0        216.0
M5 (Bina)                     216.0                216.0        216.0

                   P4 (Obra)  P5 (Anpara)  P6 (Renusagar)  P7 (Essar Mahan)
Mine \ Plant
M1 (Jayant)            216.0        216.0           216.0             216.0
M2 (Dudhichua)         216.0        216.0           216.0             216.0
M3 (Nigahi)            216.0        216.0           216.0             216.0
M4 (Krishnashila)      216.0        216.0           216.0             216.0
M5 (Bina)              216.0        216.0           216.0             216.0

In [163]:
cost_matrix.to_csv("../Outputs/cost_matrix_derived.csv")

## **Calculating Mean Demand (μ)**

###  Mean demand for each plant (tonnes per month)
###  Formula: Capacity (MW) * PLF * SCC * Hours       
###           Capacity (MW) × 0.85 × 0.55 × 720

In [164]:
plants['mean_demand']= plants['Capacity (MW)'] * 0.85 * 0.55 * 720
print(plants[['Plant Name', 'Capacity (MW)', 'mean_demand']])

                          Plant Name  Capacity (MW)  mean_demand
0          Vindhyachal Super Thermal           4760    1602216.0
1            Singrauli Super Thermal           2000     673200.0
2               Rihand Super Thermal           3000    1009800.0
3         Obra Thermal Power Project           2920     982872.0
4       Anpara Thermal Power Station           3850    1295910.0
5    Renusagar Thermal Power Station            725     244035.0
6  Essar Mahan Thermal Power Project            600     201960.0

## **Calculating Standard Deviation (σ)**

### Standard deviation = 15% of mean demand
### CV = 0.15  Coefficient of variation

In [165]:
cv = 0.15
plants['std_dev'] = plants['mean_demand']*cv
print(plants['std_dev'])

0    240332.40
1    100980.00
2    151470.00
3    147430.80
4    194386.50
5     36605.25
6     30294.00
Name: std_dev, dtype: float64

In [166]:
plants.to_csv("../Outputs/plants_updated.csv")

## **Extract Mine Supplies**

In [167]:
# Extract supply and demand arrays
supply = mines['Monthly Supply (tonnes)'].values
demand = plants['mean_demand'].values

print("Supply array:", supply)
print("Demand array:", demand)

Supply array: [2500000. 2083333. 2083333.  583333.  916667.  916667.  916667.  750000.
  583333.  416667.]
Demand array: [1602216.  673200. 1009800.  982872. 1295910.  244035.  201960.]

In [168]:
print(f"\nNumber of mines: {len(supply)}")
print(f"Number of plants: {len(demand)}")
print(f"Cost matrix shape: {cost_matrix.shape}")

Number of mines: 10
Number of plants: 7
Cost matrix shape: (10, 7)

## **Building Constraints**

In [169]:
## Constraints Setup (will be shared by deterministic + stochastic)

n_mines = len(supply)    
n_plants = len(demand)  

# Decision variable x is a flat vector of length 10×7 = 70
# x[i*n_plants + j] = tonnes from mine i to plant j

# 1.) Supply constraint: sum of shipments from mine i ≤ supply[i] ---
# Shape: (n_mines, n_mines*n_plants)
A_supply = np.zeros((n_mines, n_mines * n_plants))
for i in range(n_mines):
    for j in range(n_plants):
        A_supply[i, i * n_plants + j] = 1
b_supply = supply  # RHS: each mine's monthly supply cap

# 2.) Minimum delivery constraint: total received at plant j ≥ 0.65 * demand[j] ---
# Rewritten as: -sum(xij for all i) ≤ -0.65 * demand[j]
A_demand = np.zeros((n_plants, n_mines * n_plants))
for j in range(n_plants):
    for i in range(n_mines):
        A_demand[j, i * n_plants + j] = -1
b_demand = -0.65 * demand  # ← 65% floor, NOT 100%

# Combine
A_ub = np.vstack([A_supply, A_demand])
b_ub = np.concatenate([b_supply, b_demand])

# Non-negativity
bounds = [(0, None)] * (n_mines * n_plants)

print(f"A_ub shape: {A_ub.shape}")  # Should be (17, 70)
print(f"b_ub shape: {b_ub.shape}")  # Should be (17,)

A_ub shape: (17, 70)
b_ub shape: (17,)

## **Deterministic Solution**

#### What's the cheapest way to ship coal from mines to plants, given known fixed demand? The randomness part will be solved using stochastic optimization below in the notebook

In [170]:
from scipy.optimize import linprog

## Deterministic Optimization
# Objective: minimize sum of (cost_per_tonne * tonnes_shipped) across all routes
c = cost_matrix.values.flatten()  # Shape (70,) — transport cost per tonne

result_det = linprog(
    c,
    A_ub=A_ub,
    b_ub=b_ub,
    bounds=bounds,
    method='highs'
)

print("=" * 50)
print("DETERMINISTIC LP RESULT")
print("=" * 50)
print(f"Status  : {result_det.message}")
print(f"Success : {result_det.success}")
print(f"Total Transport Cost: ₹{result_det.fun:,.0f}")

==================================================
DETERMINISTIC LP RESULT
==================================================
Status  : Optimization terminated successfully. (HiGHS Status 7: Optimal)
Success : True
Total Transport Cost: ₹843,803,017

In [171]:
if result_det.success:
    x_det = result_det.x.reshape(n_mines, n_plants)
    allocation_det = pd.DataFrame(
        x_det,
        index=mines['Mine Name'],
        columns=plants['Plant Name']
    )

    print("\nOptimal Allocation — Deterministic (tonnes/month):")
    print(allocation_det.round(0).to_string())

    # Verify supply not exceeded
    print("\n--- Supply Check ---")
    for i, mine in enumerate(mines['Mine Name']):
        used = x_det[i].sum()
        cap = supply[i]
        print(f"{mine:20s}: used {used:>12,.0f} / available {cap:>12,.0f}  {'✓' if used <= cap + 1 else '✗ EXCEEDED'}")

    # Verify demand floors met
    print("\n--- Demand Check (≥65%) ---")
    for j, plant in enumerate(plants['Plant Name']):
        received = x_det[:, j].sum()
        required = 0.65 * demand[j]
        pct = received / demand[j] * 100
        print(f"{plant:20s}: received {received:>12,.0f} | 65% floor {required:>12,.0f} | {pct:.1f}%  {'✓' if received >= required - 1 else '✗ BELOW FLOOR'}")
else:
    print("Solver failed:", result_det.message)

Optimal Allocation — Deterministic (tonnes/month):
Plant Name    Vindhyachal Super Thermal  Singrauli Super Thermal  Rihand Super Thermal  Obra Thermal Power Project  Anpara Thermal Power Station  Renusagar Thermal Power Station  Essar Mahan Thermal Power Project
Mine Name
Jayant                              0.0                      0.0              656370.0                    638867.0                      842342.0                              0.0                           131274.0
Dudhichua                           0.0                 437580.0                   0.0                         0.0                           0.0                              0.0                                0.0
Nigahi                              0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Krishnashila                        0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Bina                           624773.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Kakri                               0.0                      0.0                   0.0                         0.0                           0.0                         158623.0                                0.0
Khadia                              0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Amlohri                             0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Block-B                             0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Jhingurda                      416667.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0

--- Supply Check ---
Jayant              : used    2,268,852 / available    2,500,000  ✓
Dudhichua           : used      437,580 / available    2,083,333  ✓
Nigahi              : used            0 / available    2,083,333  ✓
Krishnashila        : used            0 / available      583,333  ✓
Bina                : used      624,773 / available      916,667  ✓
Kakri               : used      158,623 / available      916,667  ✓
Khadia              : used            0 / available      916,667  ✓
Amlohri             : used            0 / available      750,000  ✓
Block-B             : used            0 / available      583,333  ✓
Jhingurda           : used      416,667 / available      416,667  ✓

--- Demand Check (≥65%) ---
Vindhyachal Super Thermal: received    1,041,440 | 65% floor    1,041,440 | 65.0%  ✓
Singrauli Super Thermal: received      437,580 | 65% floor      437,580 | 65.0%  ✓
Rihand Super Thermal: received      656,370 | 65% floor      656,370 | 65.0%  ✓
Obra Thermal Power Project: received      638,867 | 65% floor      638,867 | 65.0%  ✓
Anpara Thermal Power Station: received      842,342 | 65% floor      842,342 | 65.0%  ✓
Renusagar Thermal Power Station: received      158,623 | 65% floor      158,623 | 65.0%  ✓
Essar Mahan Thermal Power Project: received      131,274 | 65% floor      131,274 | 65.0%  ✓

## Observation :
Every plant is sitting exactly at 65.0%, this is a red flag.
The optimizer is doing the minimum legally allowed. It's not trying to meet full demand because your objective only minimizes transport cost, and there's no penalty in the objective function for delivering only 65%. So it rationally says "why ship more expensive coal when I don't have to?"
This is actually correct LP behavior, it's not a bug, it's telling you something real: without penalizing shortfalls in the objective, the model will always hug the 65% floor. The stochastic model fixes this by adding expected penalty cost to the objective.

## **Solution Using Stochastic Optimization**

In [172]:
## Stochastic Optimization

np.random.seed(42)  # for reproducibility
K = 1000  # number of demand scenarios

# Shape: (1000, 7) — each row is one possible demand scenario
demand_samples = np.random.normal(
    loc=plants['mean_demand'].values,
    scale=plants['std_dev'].values,
    size=(K, n_plants)
)

# Clip negative demands (normal dist can go negative for small plants)
demand_samples = np.clip(demand_samples, 0, None)

print(f"Demand samples shape: {demand_samples.shape}")
print(f"Sample mean (should ≈ mean_demand): {demand_samples.mean(axis=0).round(0)}")
print(f"Sample std  (should ≈ std_dev)    : {demand_samples.std(axis=0).round(0)}")

Demand samples shape: (1000, 7)
Sample mean (should ≈ mean_demand): [1600989.  671154. 1013064.  978640. 1283098.  245517.  202295.]
Sample std  (should ≈ std_dev)    : [239882. 102971. 151578. 149281. 194540.  36718.  29559.]

### Objective Function

In [173]:
BASE_PRICE = 4200

def stochastic_objective_v2(x_flat):
    x = x_flat.reshape(n_mines, n_plants)
    transport_cost = np.sum(cost_matrix.values * x)
    received = x.sum(axis=0)
    shortfall = np.maximum(0, demand_samples - received[np.newaxis, :])
    ratio = received[np.newaxis, :] / np.maximum(demand_samples, 1)
    pen_mid  = 0.015 * BASE_PRICE * shortfall * ((ratio >= 0.65) & (ratio < 0.80))
    pen_high = 0.10  * BASE_PRICE * shortfall * (ratio < 0.65)
    return transport_cost + (pen_mid + pen_high).sum() / K

In [174]:
from scipy.optimize import minimize

# Supply constraints: sum of row i ≤ supply[i]
# Written as: supply[i] - sum(x[i,j] for j) ≥ 0
supply_constraints = []
for i in range(n_mines):
    def supply_con(x_flat, i=i):
        x = x_flat.reshape(n_mines, n_plants)
        return supply[i] - x[i, :].sum()
    supply_constraints.append({'type': 'ineq', 'fun': supply_con})

# Demand floor constraints: received at plant j ≥ 0.65 * mean_demand[j]
# Using MEAN demand here (not sampled) — this is a baseline safety floor
demand_constraints = []
for j in range(n_plants):
    def demand_con(x_flat, j=j):
        x = x_flat.reshape(n_mines, n_plants)
        return x[:, j].sum() - 0.65 * demand[j]
    demand_constraints.append({'type': 'ineq', 'fun': demand_con})

all_constraints = supply_constraints + demand_constraints

# Bounds: all allocations ≥ 0
bounds_stoch = [(0, None)] * (n_mines * n_plants)

In [175]:
# Warm start: scale deterministic solution up to 80% delivery
x0_better = result_det.x * (0.80 / 0.65)

# Clip so no mine exceeds its supply
x0_better = x0_better.reshape(n_mines, n_plants)
for i in range(n_mines):
    row_sum = x0_better[i].sum()
    if row_sum > supply[i]:
        x0_better[i] *= supply[i] / row_sum
x0_better = x0_better.flatten()

result_stoch_v2 = minimize(
    stochastic_objective_v2,
    x0_better,
    method='SLSQP',
    bounds=bounds_stoch,
    constraints=all_constraints,
    options={'maxiter': 2000, 'ftol': 1e-8, 'disp': True}
)

print(f"Success : {result_stoch_v2.success}")
print(f"Message : {result_stoch_v2.message}")
print(f"Total Expected Cost: ₹{result_stoch_v2.fun:,.0f}")

Optimization terminated successfully    (Exit mode 0)
            Current function value: 1244333141.6348093
            Iterations: 155
            Function evaluations: 11451
            Gradient evaluations: 155
Success : True
Message : Optimization terminated successfully
Total Expected Cost: ₹1,244,333,142

In [176]:
if result_stoch_v2.success:
    x_stoch_v2 = result_stoch_v2.x.reshape(n_mines, n_plants)
    allocation_stoch = pd.DataFrame(
        x_stoch_v2,
        index=mines['Mine Name'],
        columns=plants['Plant Name']
    )
    print("\nOptimal Allocation — Stochastic (tonnes/month):")
    print(allocation_stoch.round(0).to_string())

    print("\n--- Supply Check ---")
    for i, mine in enumerate(mines['Mine Name']):
        used = x_stoch_v2[i].sum()
        cap = supply[i]
        print(f"{mine:20s}: used {used:>12,.0f} / available {cap:>12,.0f}  {'✓' if used <= cap + 1 else '✗ EXCEEDED'}")

    print("\n--- Demand Check ---")
    for j, plant in enumerate(plants['Plant Name']):
        received = x_stoch_v2[:, j].sum()
        pct = received / demand[j] * 100
        print(f"{plant:25s}: {received:>12,.0f} tonnes | {pct:.1f}% of mean demand")

    # Transport cost
    transport_only = np.sum(cost_matrix.values * x_stoch_v2)

    # Recompute expected penalty cleanly (without sparsity term)
    received_v3  = x_stoch_v2.sum(axis=0)
    shortfall_v3 = np.maximum(0, demand_samples - received_v3[np.newaxis, :])
    ratio_v3     = received_v3[np.newaxis, :] / np.maximum(demand_samples, 1)
    pen_mid_v3   = 0.015 * BASE_PRICE * shortfall_v3 * ((ratio_v3 >= 0.65) & (ratio_v3 < 0.80))
    pen_high_v3  = 0.10  * BASE_PRICE * shortfall_v3 * (ratio_v3 < 0.65)
    expected_pen = (pen_mid_v3 + pen_high_v3).sum() / K

    print(f"\n--- Cost Breakdown ---")
    print(f"Transport cost   : ₹{transport_only:>15,.0f}")
    print(f"Expected penalty : ₹{expected_pen:>15,.0f}")
    print(f"Total            : ₹{transport_only + expected_pen:>15,.0f}")

else:
    print("Solver failed:", result_stoch_v2.message)

Optimal Allocation — Stochastic (tonnes/month):
Plant Name    Vindhyachal Super Thermal  Singrauli Super Thermal  Rihand Super Thermal  Obra Thermal Power Project  Anpara Thermal Power Station  Renusagar Thermal Power Station  Essar Mahan Thermal Power Project
Mine Name
Jayant                           3910.0                   1362.0              709089.0                    689555.0                      913908.0                           2911.0                           129528.0
Dudhichua                        3910.0                 504129.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Nigahi                           3910.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Krishnashila                     3910.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Bina                           750531.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Kakri                            3910.0                   1362.0                2470.0                      2222.0                        1700.0                         167606.0                             1501.0
Khadia                           3910.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Amlohri                          3910.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Block-B                          3910.0                   1362.0                2470.0                      2222.0                        1700.0                           2911.0                             1501.0
Jhingurda                      398246.0                     29.0                  18.0                         2.0                        1174.0                            442.0                             2069.0

--- Supply Check ---
Jayant              : used    2,450,261 / available    2,500,000  ✓
Dudhichua           : used      518,843 / available    2,083,333  ✓
Nigahi              : used       16,075 / available    2,083,333  ✓
Krishnashila        : used       16,075 / available      583,333  ✓
Bina                : used      762,696 / available      916,667  ✓
Kakri               : used      180,770 / available      916,667  ✓
Khadia              : used       16,075 / available      916,667  ✓
Amlohri             : used       16,075 / available      750,000  ✓
Block-B             : used       16,075 / available      583,333  ✓
Jhingurda           : used      401,981 / available      416,667  ✓

--- Demand Check ---
Vindhyachal Super Thermal:    1,180,058 tonnes | 73.7% of mean demand
Singrauli Super Thermal  :      515,052 tonnes | 76.5% of mean demand
Rihand Super Thermal     :      728,864 tonnes | 72.2% of mean demand
Obra Thermal Power Project:      707,333 tonnes | 72.0% of mean demand
Anpara Thermal Power Station:      928,683 tonnes | 71.7% of mean demand
Renusagar Thermal Power Station:      191,336 tonnes | 78.4% of mean demand
Essar Mahan Thermal Power Project:      143,603 tonnes | 71.1% of mean demand

--- Cost Breakdown ---
Transport cost   : ₹    949,304,403
Expected penalty : ₹    295,028,739
Total            : ₹  1,244,333,142

In [177]:
# Recompute stochastic costs from v3 result for comparison tables
transport_stoch = compute_transport_cost(x_stoch_v2)
penalty_stoch   = compute_expected_penalty(x_stoch_v2)
total_stoch     = transport_stoch + penalty_stoch

In [178]:
print("=" * 75)
print(f"{'SCENARIO':<30} {'TRANSPORT':>14} {'EXP. PENALTY':>14} {'TOTAL':>14}")
print("=" * 75)
print(f"{'Deterministic':<30} ₹{transport_det:>13,.0f} ₹{penalty_det:>13,.0f} ₹{total_det:>13,.0f}")
print(f"{'Stochastic':<30} ₹{transport_stoch:>13,.0f} ₹{penalty_stoch:>13,.0f} ₹{total_stoch:>13,.0f}")
print("=" * 75)
print(f"\nKey insight: Stochastic ships more coal (higher transport cost) but")
print(f"dramatically reduces penalty exposure, saving ₹{total_det - total_stoch:,.0f} overall.")

===========================================================================
SCENARIO                            TRANSPORT   EXP. PENALTY          TOTAL
===========================================================================
Deterministic                  ₹  843,803,017 ₹  621,903,853 ₹1,465,706,870
Stochastic                     ₹  949,304,403 ₹  295,028,739 ₹1,244,333,142
===========================================================================

Key insight: Stochastic ships more coal (higher transport cost) but
dramatically reduces penalty exposure, saving ₹221,373,729 overall.

### In practice, coal is transported in full train rakes of ~4,000 tonnes. Our continuous LP solution produces non-integer allocations (e.g., 3,910 tonnes on a route). Enforcing rake-sized shipments would require Integer Linear Programming (ILP), which is beyond the scope of this course. Post-processing rounding to the nearest rake introduces a cost deviation of less than 0.5%, which we acknowledge as a modeling limitation.

## **Implementing Naive's Baseline for Comparison**

In [179]:
## Naive Baseline — Nearest Mine First (Current Industry Practice)
# Logic: for each plant, assign coal from closest mine first,
# then next closest if first mine runs out. No optimization.

# Step 1: Work with a copy of supply so we can deplete it as we allocate
remaining_supply = supply.copy().astype(float)

# Step 2: Initialize allocation matrix (10 mines × 7 plants)
x_naive = np.zeros((n_mines, n_plants))

# Step 3: For each plant, greedily assign from nearest mine
for j in range(n_plants):
    required = demand[j]  # use mean demand as target
    
    # Sort mines by distance to this plant (closest first)
    mine_distances = distances.iloc[:, j].values  # distance from each mine to plant j
    sorted_mines = np.argsort(mine_distances)      # indices sorted by distance
    
    for i in sorted_mines:
        if required <= 0:
            break  # plant's demand fully met
        
        # Take as much as this mine can still give
        allocated = min(remaining_supply[i], required)
        x_naive[i, j] = allocated
        remaining_supply[i] -= allocated
        required -= allocated

# Step 4: Display allocation
allocation_naive = pd.DataFrame(
    x_naive,
    index=mines['Mine Name'],
    columns=plants['Plant Name']
)

print("Naive Allocation (tonnes/month):")
print(allocation_naive.round(0).to_string())

Naive Allocation (tonnes/month):
Plant Name    Vindhyachal Super Thermal  Singrauli Super Thermal  Rihand Super Thermal  Obra Thermal Power Project  Anpara Thermal Power Station  Renusagar Thermal Power Station  Essar Mahan Thermal Power Project
Mine Name
Jayant                              0.0                      0.0               35217.0                         0.0                           0.0                              0.0                                0.0
Dudhichua                           0.0                      0.0                   0.0                    982872.0                           0.0                              0.0                                0.0
Nigahi                         435550.0                 673200.0              974583.0                         0.0                           0.0                              0.0                                0.0
Krishnashila                   583333.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Bina                                0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Kakri                               0.0                      0.0                   0.0                         0.0                      379243.0                         244035.0                                0.0
Khadia                              0.0                      0.0                   0.0                         0.0                      916667.0                              0.0                                0.0
Amlohri                             0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Block-B                        583333.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Jhingurda                           0.0                      0.0                   0.0                         0.0                           0.0                              0.0                           201960.0

In [180]:
# Supply check
print("\n--- Supply Check ---")
for i, mine in enumerate(mines['Mine Name']):
    used = x_naive[i].sum()
    cap = supply[i]
    print(f"{mine:20s}: used {used:>12,.0f} / available {cap:>12,.0f}  {'✓' if used <= cap + 1 else '✗ EXCEEDED'}")

# Demand fulfillment check
print("\n--- Demand Check ---")
for j, plant in enumerate(plants['Plant Name']):
    received = x_naive[:, j].sum()
    pct = received / demand[j] * 100
    print(f"{plant:25s}: {received:>12,.0f} tonnes | {pct:.1f}% of mean demand")

# Cost computation — same helper functions you already have
transport_naive = compute_transport_cost(x_naive)
penalty_naive   = compute_expected_penalty(x_naive)
total_naive     = transport_naive + penalty_naive

print(f"\n--- Naive Cost Breakdown ---")
print(f"Transport cost   : ₹{transport_naive:>15,.0f}")
print(f"Expected penalty : ₹{penalty_naive:>15,.0f}")
print(f"Total            : ₹{total_naive:>15,.0f}")

--- Supply Check ---
Jayant              : used       35,217 / available    2,500,000  ✓
Dudhichua           : used      982,872 / available    2,083,333  ✓
Nigahi              : used    2,083,333 / available    2,083,333  ✓
Krishnashila        : used      583,333 / available      583,333  ✓
Bina                : used            0 / available      916,667  ✓
Kakri               : used      623,278 / available      916,667  ✓
Khadia              : used      916,667 / available      916,667  ✓
Amlohri             : used            0 / available      750,000  ✓
Block-B             : used      583,333 / available      583,333  ✓
Jhingurda           : used      201,960 / available      416,667  ✓

--- Demand Check ---
Vindhyachal Super Thermal:    1,602,216 tonnes | 100.0% of mean demand
Singrauli Super Thermal  :      673,200 tonnes | 100.0% of mean demand
Rihand Super Thermal     :    1,009,800 tonnes | 100.0% of mean demand
Obra Thermal Power Project:      982,872 tonnes | 100.0% of mean demand
Anpara Thermal Power Station:    1,295,910 tonnes | 100.0% of mean demand
Renusagar Thermal Power Station:      244,035 tonnes | 100.0% of mean demand
Essar Mahan Thermal Power Project:      201,960 tonnes | 100.0% of mean demand

--- Naive Cost Breakdown ---
Transport cost   : ₹  1,298,158,488
Expected penalty : ₹      6,035,098
Total            : ₹  1,304,193,586

In [181]:
print("=" * 75)
print(f"{'SCENARIO':<30} {'TRANSPORT':>14} {'EXP. PENALTY':>14} {'TOTAL':>14}")
print("=" * 75)
print(f"{'Naive (nearest mine)':<30} ₹{transport_naive:>13,.0f} ₹{penalty_naive:>13,.0f} ₹{total_naive:>13,.0f}")
print(f"{'Deterministic LP':<30} ₹{transport_det:>13,.0f} ₹{penalty_det:>13,.0f} ₹{total_det:>13,.0f}")
print(f"{'Stochastic':<30} ₹{transport_stoch:>13,.0f} ₹{penalty_stoch:>13,.0f} ₹{total_stoch:>13,.0f}")
print("=" * 75)

saving_det   = total_naive - total_det
saving_stoch = total_naive - total_stoch

print(f"\nSavings — Deterministic vs Naive : ₹{saving_det:>15,.0f}  ({saving_det/total_naive*100:.1f}%)")
print(f"Savings — Stochastic vs Naive    : ₹{saving_stoch:>15,.0f}  ({saving_stoch/total_naive*100:.1f}%)")
print(f"\nAdditional gain from Stochastic over Deterministic: ₹{total_det - total_stoch:,.0f}")

===========================================================================
SCENARIO                            TRANSPORT   EXP. PENALTY          TOTAL
===========================================================================
Naive (nearest mine)           ₹1,298,158,488 ₹    6,035,098 ₹1,304,193,586
Deterministic LP               ₹  843,803,017 ₹  621,903,853 ₹1,465,706,870
Stochastic                     ₹  949,304,403 ₹  295,028,739 ₹1,244,333,142
===========================================================================

Savings — Deterministic vs Naive : ₹   -161,513,285  (-12.4%)
Savings — Stochastic vs Naive    : ₹     59,860,444  (4.6%)

Additional gain from Stochastic over Deterministic: ₹221,373,729

### Note: Naive delivers 100% of mean demand by design (greedy fill).
### Deterministic enforces only 65% floor (cost-minimizing constraint).
### Stochastic self-selects ~72-78% delivery as the optimal risk balance.
### All three are evaluated on the same 1000 demand samples for fair comparison.

##### The naive heuristic minimizes penalty risk by over-delivering coal but wastes ₹59.8 crore monthly in suboptimal transport routing. The deterministic LP finds the cheapest routes but treats demand as certain when evaluated against real demand uncertainty, its 65% delivery floor triggers massive penalties, making it the worst performer overall. The stochastic model explicitly balances transport cost against expected penalty, achieving the lowest total expected cost by shipping slightly more coal on slightly costlier routes as a deliberate hedge against demand volatility.

## **Sensitivity Analysis**

### We tried to perform specifically in these scenarios :
1.) Nigahi Mines supply drops by  20%      
2.) Vindhyachal Mines demand increases by 30%        
3.) Freight rates increases by 10%

In [182]:
## Sensitivity Analysis
# Base result for comparison
base_total = result_stoch_v2.fun
print(f"Base Stochastic Total Cost: ₹{base_total:,.0f}")

def run_stochastic(supply_arr, demand_arr, cost_arr, demand_samples_arr, label):
    """
    Re-runs stochastic optimization with modified inputs.
    Returns total expected cost and allocation matrix.
    """
    n_m = len(supply_arr)
    n_p = len(demand_arr)
    
    # Rebuild constraints with new supply/demand
    sup_constraints = []
    for i in range(n_m):
        def sup_con(x_flat, i=i):
            return supply_arr[i] - x_flat.reshape(n_m, n_p)[i, :].sum()
        sup_constraints.append({'type': 'ineq', 'fun': sup_con})
    
    dem_constraints = []
    for j in range(n_p):
        def dem_con(x_flat, j=j):
            return x_flat.reshape(n_m, n_p)[:, j].sum() - 0.65 * demand_arr[j]
        dem_constraints.append({'type': 'ineq', 'fun': dem_con})
    
    all_cons = sup_constraints + dem_constraints
    bounds_s = [(0, None)] * (n_m * n_p)
    
    # Objective
    def obj(x_flat):
        x = x_flat.reshape(n_m, n_p)
        transport = np.sum(cost_arr * x)
        received = x.sum(axis=0)
        shortfall = np.maximum(0, demand_samples_arr - received[np.newaxis, :])
        ratio = received[np.newaxis, :] / np.maximum(demand_samples_arr, 1)
        pen_mid  = 0.015 * BASE_PRICE * shortfall * ((ratio >= 0.65) & (ratio < 0.80))
        pen_high = 0.10  * BASE_PRICE * shortfall * (ratio < 0.65)
        return transport + (pen_mid + pen_high).sum() / K
    
    # Warm start from base stochastic solution
    x0 = x_stoch_v2.flatten() * (0.80 / 0.65)
    x0 = x0.reshape(n_m, n_p)
    for i in range(n_m):
        row_sum = x0[i].sum()
        if row_sum > supply_arr[i]:
            x0[i] *= supply_arr[i] / row_sum
    x0 = x0.flatten()
    
    result = minimize(obj, x0, method='SLSQP', bounds=bounds_s,
                      constraints=all_cons,
                      options={'maxiter': 2000, 'ftol': 1e-8, 'disp': False})
    
    print(f"\n{label}")
    print(f"  Success : {result.success}")
    print(f"  Total Expected Cost: ₹{result.fun:,.0f}")
    print(f"  Change from base  : ₹{result.fun - base_total:,.0f}  ({(result.fun - base_total)/base_total*100:+.2f}%)")
    
    return result

Base Stochastic Total Cost: ₹1,244,333,142

## Scenario 1

In [183]:
# Nigahi is index 2 in your mines dataframe — verify with:
print(mines['Mine Name'].tolist())  # check index 2 is Nigahi

supply_s1 = supply.copy()
supply_s1[2] *= 0.80  # Nigahi supply reduced 20%

print(f"Nigahi original supply : {supply[2]:,.0f}")
print(f"Nigahi reduced supply  : {supply_s1[2]:,.0f}")

result_s1 = run_stochastic(
    supply_s1, demand, cost_matrix.values,
    demand_samples, "Scenario 1: Nigahi Supply ↓ 20%"
)

['Jayant', 'Dudhichua', 'Nigahi', 'Krishnashila', 'Bina', 'Kakri', 'Khadia', 'Amlohri', 'Block-B', 'Jhingurda']
Nigahi original supply : 2,083,333
Nigahi reduced supply  : 1,666,666

Scenario 1: Nigahi Supply ↓ 20%
  Success : True
  Total Expected Cost: ₹1,201,858,656
  Change from base  : ₹-42,474,486  (-3.41%)

Scneario 2

In [184]:
# Vindhyachal is index 0 in your plants dataframe — verify with:
print(plants['Plant Name'].tolist())  # check index 0 is Vindhyachal

demand_s2 = demand.copy()
demand_s2[0] *= 1.30  # Vindhyachal mean demand up 30%

# Also regenerate demand samples with new mean for Vindhyachal
std_dev_s2 = plants['std_dev'].values.copy()
std_dev_s2[0] = demand_s2[0] * 0.15  # std dev scales with mean

demand_samples_s2 = np.random.normal(
    loc=demand_s2,
    scale=std_dev_s2,
    size=(K, n_plants)
)
demand_samples_s2 = np.clip(demand_samples_s2, 0, None)

print(f"Vindhyachal original demand : {demand[0]:,.0f}")
print(f"Vindhyachal increased demand: {demand_s2[0]:,.0f}")

result_s2 = run_stochastic(
    supply, demand_s2, cost_matrix.values,
    demand_samples_s2, "Scenario 2: Vindhyachal Demand ↑ 30%"
)

['Vindhyachal Super Thermal', 'Singrauli Super Thermal', 'Rihand Super Thermal', 'Obra Thermal Power Project', 'Anpara Thermal Power Station', 'Renusagar Thermal Power Station', 'Essar Mahan Thermal Power Project']
Vindhyachal original demand : 1,602,216
Vindhyachal increased demand: 2,082,881

Scenario 2: Vindhyachal Demand ↑ 30%
  Success : True
  Total Expected Cost: ₹1,381,032,240
  Change from base  : ₹136,699,098  (+10.99%)

Scenario 3

In [185]:
cost_matrix_s3 = cost_matrix.values * 1.10  # all freight rates up 10%

result_s3 = run_stochastic(
    supply, demand, cost_matrix_s3,
    demand_samples, "Scenario 3: Freight Rates ↑ 10%"
)

Scenario 3: Freight Rates ↑ 10%
  Success : True
  Total Expected Cost: ₹1,291,904,048
  Change from base  : ₹47,570,906  (+3.82%)

In [186]:
print("\n" + "=" * 75)
print("SENSITIVITY ANALYSIS SUMMARY")
print("=" * 75)
print(f"{'Scenario':<40} {'Total Cost':>14} {'Change':>10} {'% Change':>9}")
print("=" * 75)

scenarios = [
    ("Base Stochastic",              base_total),
    ("S1: Nigahi Supply drops by 20%",      result_s1.fun),
    ("S2: Vindhyachal Demand increases by 30%", result_s2.fun),
    ("S3: Freight Rates increases by 10%",      result_s3.fun),
]

for name, cost in scenarios:
    change = cost - base_total
    pct    = change / base_total * 100
    marker = "" if name == "Base Stochastic" else f"({pct:+.2f}%)"
    print(f"{name:<40} ₹{cost:>13,.0f} ₹{change:>9,.0f}  {marker}")

print("=" * 75)

===========================================================================
SENSITIVITY ANALYSIS SUMMARY
===========================================================================
Scenario                                     Total Cost     Change  % Change
===========================================================================
Base Stochastic                          ₹1,244,333,142 ₹        0
S1: Nigahi Supply drops by 20%           ₹1,201,858,656 ₹-42,474,486  (-3.41%)
S2: Vindhyachal Demand increases by 30%  ₹1,381,032,240 ₹136,699,098  (+10.99%)
S3: Freight Rates increases by 10%       ₹1,291,904,048 ₹47,570,906  (+3.82%)
===========================================================================

### **Conclusion (1): Your network is not sensitive to Nigahi supply. It's a slack resource.**
### **Conclusion (2): Your network is most sensitive to Vindhyachal demand. It's the critical node.**
### **Conclusion (3): The network has moderate freight elasticity optimization partially absorbs rate shocks by adjusting delivery levels.**

## Limitations

**1. Simplified Penalty Structure**
The severe shortage penalty below 65% is assumed at 10% of shortfall value. Actual 
Coal India contracts may impose higher or escalating penalties. The 1.5% penalty in 
the 65–80% bracket is taken directly from Coal India contract terms but may vary by plant.

**2. Assumed Demand Variance**
Standard deviation is assumed at 15% of mean demand (CV = 0.15) due to absence of 
real historical time-series data. Actual demand volatility may differ significantly 
across seasons — summer peaks and winter lows are not captured in a static normal 
distribution.

**3. No Seasonality or Time Dimension**
The model is a single-period static model. Real coal logistics involves multi-month 
planning, inventory carryover, and seasonal demand cycles. A dynamic multi-period model 
would be more realistic but is beyond the scope of this course.

**4. Rake Constraint Not Enforced**
In practice, coal moves in full train rakes (~4,000 tonnes per rake). Enforcing this 
requires Integer Linear Programming (ILP). Our continuous LP solution was acknowledged 
as producing non-integer allocations. Post-processing rounding introduces less than 
0.5% cost deviation but is not part of the optimization itself. Thus, when our solver produces small 
spray allocations across many routes (below one rake size) due to gradient hedging 
near penalty thresholds. A global solver or integer program would produce cleaner, 
more operationally realistic allocations.

In [187]:
## Export comparison summary

comparison_data = {
    'Scenario': [
        'Naive (Nearest Mine)',
        'Deterministic LP',
        'Stochastic'
    ],
    'Transport Cost (₹)': [
        transport_naive,
        transport_det,
        transport_stoch
    ],
    'Expected Penalty (₹)': [
        penalty_naive,
        penalty_det,
        penalty_stoch
    ],
    'Total Expected Cost (₹)': [
        total_naive,
        total_det,
        total_stoch
    ],
    'Savings vs Naive (₹)': [
        0,
        total_naive - total_det,
        total_naive - total_stoch
    ],
    'Savings vs Naive (%)': [
        0,
        round((total_naive - total_det)/total_naive*100, 2),
        round((total_naive - total_stoch)/total_naive*100, 2)
    ]
}

comparison_df = pd.DataFrame(comparison_data)
comparison_df.to_csv("../Outputs/scenario_comparison.csv", index=False)
print("✓ Saved to ../Outputs/scenario_comparison.csv")

## Export sensitivity summary

sensitivity_data = {
    'Scenario': [
        'Base Stochastic',
        'S1: Nigahi Supply ↓ 20%',
        'S2: Vindhyachal Demand ↑ 30%',
        'S3: Freight Rates ↑ 10%'
    ],
    'Total Expected Cost (₹)': [
        base_total,
        result_s1.fun,
        result_s2.fun,
        result_s3.fun
    ],
    'Change from Base (₹)': [
        0,
        result_s1.fun - base_total,
        result_s2.fun - base_total,
        result_s3.fun - base_total
    ],
    'Change (%)': [
        0,
        round((result_s1.fun - base_total)/base_total*100, 2),
        round((result_s2.fun - base_total)/base_total*100, 2),
        round((result_s3.fun - base_total)/base_total*100, 2)
    ]
}

sensitivity_df = pd.DataFrame(sensitivity_data)
sensitivity_df.to_csv("../Outputs/sensitivity_analysis.csv", index=False)
print("✓ Saved to ../Outputs/sensitivity_analysis.csv")

✓ Saved to ../Outputs/scenario_comparison.csv
✓ Saved to ../Outputs/sensitivity_analysis.csv

In [188]:
x_stoch_display = x_stoch_v2.copy()

allocation_export = pd.DataFrame(
    x_stoch_display.round(0),
    index=mines['Mine Name'],
    columns=plants['Plant Name']
)

# Add totals
allocation_export['Total Shipped (tonnes)'] = allocation_export.sum(axis=1).round(0)
allocation_export.loc['Total Received (tonnes)'] = allocation_export.sum(axis=0).round(0)

# % of mean demand row
pct_row = {}
for j, plant in enumerate(plants['Plant Name']):
    received = x_stoch_v2[:, j].sum()
    pct_row[plant] = f"{received/demand[j]*100:.1f}%"
pct_row['Total Shipped (tonnes)'] = '—'
allocation_export.loc['% of Mean Demand'] = pct_row

print(allocation_export.to_string())

allocation_export.to_csv("../Outputs/stochastic_allocation.csv")
print("\n✓ Saved to ../Outputs/stochastic_allocation.csv")

Plant Name              Vindhyachal Super Thermal Singrauli Super Thermal Rihand Super Thermal Obra Thermal Power Project Anpara Thermal Power Station Renusagar Thermal Power Station Essar Mahan Thermal Power Project Total Shipped (tonnes)
Mine Name
Jayant                                     3910.0                  1362.0             709089.0                   689555.0                     913908.0                          2911.0                          129528.0              2450263.0
Dudhichua                                  3910.0                504129.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0               518843.0
Nigahi                                     3910.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0                16076.0
Krishnashila                               3910.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0                16076.0
Bina                                     750531.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0               762697.0
Kakri                                      3910.0                  1362.0               2470.0                     2222.0                       1700.0                        167606.0                            1501.0               180771.0
Khadia                                     3910.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0                16076.0
Amlohri                                    3910.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0                16076.0
Block-B                                    3910.0                  1362.0               2470.0                     2222.0                       1700.0                          2911.0                            1501.0                16076.0
Jhingurda                                398246.0                    29.0                 18.0                        2.0                       1174.0                           442.0                            2069.0               401980.0
Total Received (tonnes)                 1180057.0                515054.0             728867.0                   707333.0                     928682.0                        191336.0                          143605.0              4394934.0
% of Mean Demand                            73.7%                   76.5%                72.2%                      72.0%                        71.7%                           78.4%                             71.1%                      —

✓ Saved to ../Outputs/stochastic_allocation.csv

# **Testing new Idea By using Stochastic LP - Linearized Penalty Approach**

In [189]:
## Stochastic LP — Linearized Penalty Approach

# Step 1: For each plant, compute expected penalty rate (₹ per tonne undelivered)
# We do this by evaluating penalty across 1000 demand samples at mean delivery level
# and computing marginal cost of one less tonne delivered

def expected_penalty_rate(j, delivery_fraction=0.73):
    """
    Compute expected penalty per tonne of shortfall for plant j
    at a given delivery fraction of mean demand.
    delivery_fraction: starting estimate (we use 0.73 — midpoint of 65-80% range)
    """
    T = delivery_fraction * demand[j]
    rates = []
    for k in range(K):
        D = demand_samples[k, j]
        ratio = T / D if D > 0 else 1
        if ratio >= 0.80:
            rates.append(0)
        elif ratio >= 0.65:
            rates.append(0.015 * BASE_PRICE)
        else:
            rates.append(0.10 * BASE_PRICE)
    return np.mean(rates)

# Compute penalty rate for each plant
penalty_rates = np.array([expected_penalty_rate(j) for j in range(n_plants)])
print("Expected penalty rate per tonne shortfall (₹/tonne):")
for j, plant in enumerate(plants['Plant Name']):
    print(f"  {plant:35s}: ₹{penalty_rates[j]:.1f}/tonne")

Expected penalty rate per tonne shortfall (₹/tonne):
  Vindhyachal Super Thermal          : ₹117.0/tonne
  Singrauli Super Thermal            : ₹116.8/tonne
  Rihand Super Thermal               : ₹126.6/tonne
  Obra Thermal Power Project         : ₹115.7/tonne
  Anpara Thermal Power Station       : ₹109.6/tonne
  Renusagar Thermal Power Station    : ₹122.2/tonne
  Essar Mahan Thermal Power Project  : ₹118.7/tonne

In [190]:
# Augmented cost = transport cost + expected penalty saved by delivering one more tonne
# Delivering one more tonne to plant j saves penalty_rates[j] rupees
# So effective cost = transport_cost - penalty_savings
# We add a "delivery bonus" by subtracting penalty rate from transport cost

augmented_cost = cost_matrix.values.copy()
for j in range(n_plants):
    augmented_cost[:, j] = cost_matrix.values[:, j] - penalty_rates[j]

print("\nAugmented cost matrix (transport - penalty savings):")
print(pd.DataFrame(augmented_cost, 
                   index=mines['Mine Name'], 
                   columns=plants['Plant Name']).round(1).to_string())

Augmented cost matrix (transport - penalty savings):
Plant Name    Vindhyachal Super Thermal  Singrauli Super Thermal  Rihand Super Thermal  Obra Thermal Power Project  Anpara Thermal Power Station  Renusagar Thermal Power Station  Essar Mahan Thermal Power Project
Mine Name
Jayant                             99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Dudhichua                          99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Nigahi                             99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Krishnashila                       99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Bina                               99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Kakri                              99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Khadia                             99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Amlohri                            99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Block-B                            99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3
Jhingurda                          99.0                     99.2                  89.4                       100.3                         106.4                             93.8                               97.3

In [191]:
from scipy.optimize import linprog

c_augmented = augmented_cost.flatten()

# Use same constraints as deterministic but with 73% floor instead of 65%
# This reflects the stochastic model's natural delivery level
A_demand_stoch = np.zeros((n_plants, n_mines * n_plants))
for j in range(n_plants):
    for i in range(n_mines):
        A_demand_stoch[j, i * n_plants + j] = -1
b_demand_stoch = -0.73 * demand  # 73% floor — stochastic target

A_ub_stoch = np.vstack([A_supply, A_demand_stoch])
b_ub_stoch = np.concatenate([b_supply, b_demand_stoch])

result_stoch_lp = linprog(
    c_augmented,
    A_ub=A_ub_stoch,
    b_ub=b_ub_stoch,
    bounds=bounds,
    method='highs'
)

print(f"Success : {result_stoch_lp.success}")
print(f"Message : {result_stoch_lp.message}")

Success : True
Message : Optimization terminated successfully. (HiGHS Status 7: Optimal)

In [192]:
if result_stoch_lp.success:
    x_stoch_lp = result_stoch_lp.x.reshape(n_mines, n_plants)
    
    allocation_stoch_lp = pd.DataFrame(
        x_stoch_lp.round(0),
        index=mines['Mine Name'],
        columns=plants['Plant Name']
    )
    
    print("\nOptimal Allocation — Stochastic LP (tonnes/month):")
    print(allocation_stoch_lp.to_string())

    # Supply check
    print("\n--- Supply Check ---")
    for i, mine in enumerate(mines['Mine Name']):
        used = x_stoch_lp[i].sum()
        print(f"{mine:20s}: used {used:>12,.0f} / available {supply[i]:>12,.0f}  {'✓' if used <= supply[i]+1 else '✗'}")

    # Demand check
    print("\n--- Demand Check ---")
    for j, plant in enumerate(plants['Plant Name']):
        received = x_stoch_lp[:, j].sum()
        print(f"{plant:25s}: {received:>12,.0f} | {received/demand[j]*100:.1f}% of mean demand")

    # True expected cost
    transport_slp = np.sum(cost_matrix.values * x_stoch_lp)
    penalty_slp   = compute_expected_penalty(x_stoch_lp)
    total_slp     = transport_slp + penalty_slp

    print(f"\n--- Cost Breakdown ---")
    print(f"Transport cost   : ₹{transport_slp:>15,.0f}")
    print(f"Expected penalty : ₹{penalty_slp:>15,.0f}")
    print(f"Total            : ₹{total_slp:>15,.0f}")

Optimal Allocation — Stochastic LP (tonnes/month):
Plant Name    Vindhyachal Super Thermal  Singrauli Super Thermal  Rihand Super Thermal  Obra Thermal Power Project  Anpara Thermal Power Station  Renusagar Thermal Power Station  Essar Mahan Thermal Power Project
Mine Name
Jayant                              0.0                      0.0              689058.0                    717497.0                      946014.0                              0.0                           147431.0
Dudhichua                           0.0                 491436.0                   0.0                         0.0                           0.0                              0.0                                0.0
Nigahi                              0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Krishnashila                        0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Bina                           752951.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Kakri                               0.0                      0.0                   0.0                         0.0                           0.0                         178146.0                                0.0
Khadia                              0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Amlohri                             0.0                      0.0               48096.0                         0.0                           0.0                              0.0                                0.0
Block-B                             0.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0
Jhingurda                      416667.0                      0.0                   0.0                         0.0                           0.0                              0.0                                0.0

--- Supply Check ---
Jayant              : used    2,500,000 / available    2,500,000  ✓
Dudhichua           : used      491,436 / available    2,083,333  ✓
Nigahi              : used            0 / available    2,083,333  ✓
Krishnashila        : used            0 / available      583,333  ✓
Bina                : used      752,951 / available      916,667  ✓
Kakri               : used      178,146 / available      916,667  ✓
Khadia              : used            0 / available      916,667  ✓
Amlohri             : used       48,096 / available      750,000  ✓
Block-B             : used            0 / available      583,333  ✓
Jhingurda           : used      416,667 / available      416,667  ✓

--- Demand Check ---
Vindhyachal Super Thermal:    1,169,618 | 73.0% of mean demand
Singrauli Super Thermal  :      491,436 | 73.0% of mean demand
Rihand Super Thermal     :      737,154 | 73.0% of mean demand
Obra Thermal Power Project:      717,497 | 73.0% of mean demand
Anpara Thermal Power Station:      946,014 | 73.0% of mean demand
Renusagar Thermal Power Station:      178,146 | 73.0% of mean demand
Essar Mahan Thermal Power Project:      147,431 | 73.0% of mean demand

--- Cost Breakdown ---
Transport cost   : ₹    947,655,696
Expected penalty : ₹    299,257,962
Total            : ₹  1,246,913,658